project: 
  type: website

website:
  description: "A blog built with Quarto"
  title: "BLOG-reproducible research course-DB"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
execute:
  freeze: auto
    

