project: 
  type: website

website:
  description: "A blog built with Quarto"
  title: "Delaram's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  sidebar: 
    - id: journal
      title: "Journal"
      style: "docked"
      contents: 
        - section: "Days"
          contents:
            - posts/Days/Monday/index.qmd
            - posts/Days/Tuesday/index.qmd
            - posts/Days/Wednesday/index.qmd
            - posts/Days/Thursday/index.qmd
            - posts/Days/Friday/index.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
execute:
  freeze: auto
    

