---
title: "Monday"
author: "Delaram Bameri"
date: "2026-09-14"
categories: [journal]
---

::: {.callout-note collapse="true" title="Monday's main take-home messages"}
Getting comfortable with Git version control and Quarto for building a reproducible blog.
:::

::: {.panel-tabset}

## What I did

1. Getting used to git version control
2. Creating an initial blog with Quarto

## What I learned

1. `git clone` — clone a repo from a GitHub link
2. `git checkout -b "branch_name"` — create your own branch
3.  Modify the required file, save it, and then check the status of your repo
4. `git status` — check what's changed
5. `git diff` — see the actual differences
6. `git add .`
7. `git commit -m "message"`
8. `git push`
9. `git fetch origin` — pull down another branch's info
10. `git merge origin/branch_name`
11. Repeat: modify → save → add → commit → push

12. Quarto is a tool for creating reproducible documents, presentations, and websites.
13. styles.css is a file that contains custom CSS styles for the blog.
14. The `_quarto.yml` file is a configuration file that defines the settings for the Quarto project, including the website title, description, and navigation bar.


## Useful links

- [Quarto documentation](https://quarto.org/docs/output-formats/html-basics.html){target="_blank"}
- [reproducible research course](https://amrei-bp.github.io/Reproducible_Research/course_blog.html){target="_blank"}

:::