
---
title: "Tuesday"
author: "Delaram Bameri"
date: "2026-09-15"
categories: [journal]
---

::: {.callout-note collapse="true" title="Tuesday's main take-home messages"}
Setting up pixi as the environment
Runnig fastqc and multiqc for the downloaded data.
Using containers to run the tools in a reproducible way.
:::

::: {.panel-tabset}

## What I did in summary

1. Pixi environment setups
2. adding required packages to the pixi environment
3. run required packages in the pixi environment
4. used screen (similar to tmux session) to run the pixi environment in the background
5. worked on the WGS data.
6. used fastqc and multiqc for the downloaded data.
7. checked slurm files after submitting the jobs and checked the output files.
8. used bash scripts to be efficient using differnt tools. 
9. try to organize the files and directories in a better way while working on the server.


## What I have done and learned with pixi environment

1. logged into the server: 
    - ssh delaramb@kebnekaise.hpc2n.umu.se
2. download pixi via webget if not installed: 
    wget -qO- https://pixi.sh/install.sh | sh
    source ~/.bashrc (on the server, linux)
3. set up the pixi environment:
    - pixi init <name_pixi_training> -c conda-forge -c bioconda
    - toml file is created 
4. adding dependencies (required packages for the pixi environment):
    - pixi add <package_name>
    - pixi run <package_name> to run the package in the pixi environment --help or other flags can be used to check the usage of the package
5. Note: on other servers such as uppmax or local we can also do 1) pixi sell 2) <package_name> --help 3) exit
6. screen -S <name_of_the session> 
7. ctrl + a d to detach the session and ctrl -r <name_of_the_session> to reattach the session, screen -ls to list the sessions 
8. soft link of the WGS data to my own directory under project_dir  (ln -s)
9. zcat <file>| head -n 10
10. man can initiate the pixi environment without naming it. so on the same directory the pixi environment can be initiated by just typing pixi init and then adding the required packages.
11. scrun -A <compute_proj_ID> -t <time> -n <number_of_nodes> pixi run <tools and the commands for the tools> 
ex: srun -A project_ID -t 15:00 -n 1 pixi run fastqc --noextract -o fastqc data/sampleA_1.fastq.gz data/sampleA_2.fastq.gz

12. I prefer to have scripts directory and the bash scripts to do the analysis. 
ex:

#! /bin/bash -l
#SBATCH -A project_ID
#SBATCH -t 30:00
#SBATCH -n 1

pixi run fastqc -o ../fastqc --noextract ../data/*fastq.gz

remember you might need: chmod+x <script_name> to make the script executable.

sbatch <script_name> to submit the job to the server.

13. we used the same approach for the multiQC analysis. 


## What I have done and learned about containers

1. Using [seqera](https://seqera.io/containers/) for the containers 
2. since we have apptainer installed on the server, then we used it to pull the container from either docker or seqera.
ex : apptainer pull vcftools_0.1.17.sif oras://community.wave.seqera.io/library/vcftools:0.1.17--b541aa8d9f9213f9
3. we should execute the container then 
ex: apptainer exec vcftools_0.1.17.sif vcftools --version
4. remember containers are like the 3D photo album, so to use it, we should open the door, get inside then we can see the content of the container. so we should use exec to get inside the container and then run the tools inside the container.
5. we ran the fastqc and the multiqc using the containers. 



## Useful links

- [Quarto documentation](https://quarto.org/docs/output-formats/html-basics.html){target="_blank"}
- [reproducible research course](https://amrei-bp.github.io/Reproducible_Research/course_blog.html){target="_blank"}

:::